package:
  name: catatonit
  version: 0.2.0
  description: minimal init system for Linux containers
  copyright:
    - license: GPL-2.0-or-later

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
      - ./melange.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - ca-certificates-bundle
      - build-base
      - busybox
      - bash
      - curl
      - automake
      - autoconf
      - libtool

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/openSUSE/catatonit
      expected-commit: 7f0c9bb45d3490c3e7f579833c9b0689f78c8923
      tag: v${{package.version}}
 
  - runs: |
      autoreconf -fiv
      ./configure --prefix=/usr
      
  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - range: libraries
    name: ${{range.key}}
    description: "${{range.value}} library"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/${{range.value}}* "${{targets.subpkgdir}}"/usr/lib/

  - name: catatonit-dev
    dependencies:
      runtime:
        - catatonit
    pipeline:
      - uses: split/dev
    description: catatonit development headers
    test:
      pipeline:
        - uses: test/pkgconf

update:
  enabled: true
  release-monitor:
    identifier: 301804
