package:
  name: catatonit
  version: 0.2.1
  description: minimal init system for Linux containers
  copyright:
    - license: GPL-2.0-or-later

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
      - ./melange.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - ca-certificates-bundle
      - build-base
      - busybox
      - bash
      - curl
      - automake
      - autoconf
      - libtool

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/openSUSE/catatonit
      expected-commit: bb3b96b99668e544618c5aec427c1f4b6b9ee9bb
      tag: v${{package.version}}
 
  - runs: |
      autoreconf -fiv
      ./configure --prefix=/usr
      
  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip
