name: Build Docker Image

on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    
    steps:
      - name: Generate snapshot date
        id: snapshot-date
        run: |
          echo "date=$(date -u +%Y%m%d)" >> $GITHUB_OUTPUT
          echo "epoch=$(date -u +%s)" >> $GITHUB_OUTPUT
        shell: bash
            
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
  
      - name: Set up Cosign
        uses: sigstore/cosign-installer@d7d6bc7722e3daa8354c50bcb52f4837da5e9b6a # v3.8.1
  
      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 #v3.3.0
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
      
      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@a13eda877cb779461da1de25f0991398d655b35c

      - name: Install Melange
        run: brew install melange

      - name: Build PKG
        run: |
          melange keygen
          melange build --runner=docker --signing-key melange.rsa --arch amd64 .melange.yaml

      - uses: distroless/actions/apko-snapshot@main
        id: apko
        with:
          keyring-append: ./melange.rsa.pub
          source-date-epoch: ${{ steps.snapshot-date.outputs.epoch }}
          additional-tags: 1.0.0
          archs: amd64
          slsa-attest: "true"
          sbom-attest: "true"
  
      - name: Generate Trivy Vulnerability Report
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.apko.outputs.digest }}
          output: trivy-report.json
          format: json
          exit-code: 0
          vuln-type: 'os,library'

      - name: Upload Vulnerability Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.json
          retention-days: 30
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.apko.outputs.digest }}
          format: 'table'
          exit-code: '1'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
