name: Build Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

    - uses: distroless/actions/apko-build@main
      with:
        config: wolfi-dotnet-runtime-deps.yaml
        tag: ghcr.io/d4rkfella/wolfi-dotnet-runtime-deps
    
