name: Build Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write
    
    steps:
    - uses: distroless/actions/apko-publish@main
      with:
        config: wolfi-dotnet-runtime-deps.yaml
        tag: ghcr.io/d4rkfella/wolfi-dotnet-runtime-deps:latest ghcr.io/d4rkfella/wolfi-dotnet-runtime-deps:1.0.0
    
    - shell: bash
      run: |
        COSIGN_EXPERIMENTAL=true cosign sign ${{ steps.apko.outputs.digest }}
